<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
          "http://www.w3.org/TR/html4/loose.dtd">
<!--  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
       "http://www.w3.org/TR/html4/strict.dtd"> -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta name="description" content="JVerein">
    <meta name="keywords" content="Vereinsverwaltung, JVerein, Verein, Open Source, OpenSource, Buchführung, Jameica, Hibiscus, Java, Linux, Windows, MacOS">
    <meta name="robots" content="index, follow">
    <meta http-equiv="expires" content="Sat, 01 Dec 2001 00:00:00 GMT">
    <link rel="SHORTCUT ICON" href="images/favicon.ico" type="image/x-icon">
    <title>JVerein - Open Source Vereinsverwaltung</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

<div id="Seite">
           <div style="text-align: right;background-color: white;">
              <span><img src='images/JVerein.png'></span><br><br><br><br><br><br>
              <span style="color: #000000; font-size: 14pt;">Open Source Vereinsverwaltung</span>
            </div>
  <p id="Kopf">&nbsp;
  <?
  $datum = getdate();
  echo date("d.m.Y H:i");
  ?>
  </p>

<div id="tabsI">
  <ul>
    <li><a href="index.php" title="Home"><span>Home</span></a></li>
    <li><a href="dokumentation.php" title="Dokumentation"><span>Dokumentation</span></a></li>
    <li><a href="changelog.php" title="Changelog"><span>Changelog</span></a></li>
    <li><a href="download.php" title="Download"><span>Download</span></a></li>
    <li><a href="installation.php" title="Installation"><span>Installation</span></a></li>
    <li><a href="cvs.php" title="CVS"><span>CVS</span></a></li>
	<li><a href="mailliste.php" title="Mailliste"><span>Mailliste</span></a></li>
	<li><a href="kontakt.php" title="Kontakt"><span>Kontakt</span></a></li>
	<li><a href="danksagung.php" title="Danksagung"><span>Danksagung</span></a></li>
  </ul>
</div>

  <div id="Inhalt">
  <br><br>
    <!-- 
    $Log$
    Revision 1.3  2009/08/20 20:15:32  jost
    *** empty log message ***

    Revision 1.2  2009/08/17 18:52:44  jost
    neues Layout

    Revision 1.1  2009/05/08 14:46:22  jost
    shtml - php

    Revision 1.17  2009/05/03 15:33:30  jost
    Neue Homepage

    -->
 
